# Generated by Django 4.1.3 on 2022-11-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='-', max_length=40, verbose_name='Автор')),
                ('email', models.EmailField(max_length=50, verbose_name='Почта')),
                ('message', models.TextField(max_length=1000, verbose_name='Запись')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
        ),
    ]
