# Generated by Django 4.1.3 on 2022-11-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='active', max_length=7, verbose_name='Статус'),
        ),
    ]
